name = "<YOUR_APPNAME>_discord2telegram"
main = "./dist/index.js"
compatibility_date = "2023-11-21"

kv_namespaces = [
]

workers_dev = false

[build]
command = "npm run build"
[triggers]
crons = [ "*/5 * * * *"]
[env.dev.triggers]
crons = ["0 * * * *"]
